### PR TITLE
[sync] Staged api to 01e8bf8b (v0.8.0) and olm to c480add3.

### PR DESCRIPTION
**Pull request by benluddy**
Sync of staged upstream repos:
- api to 01e8bf8b (v0.8.0)
- olm to c480add3

### CODE REVIEW

**Review by timflannagan — COMMENTED** [review]
I think you need to run `make vendor` at the root looking at this changelog or else it will fail that verify prow job.

**Comment by benluddy** [comment]
Root manifests need to be updated too.

/hold

**Comment by timflannagan** [comment]
Hmm, that seems like a legitimate error:

```
INFO[2021-04-10T04:59:58Z] go test -v -mod=vendor  -failfast -timeout 150m ./test/e2e/... -namespace=openshift-operators -kubeconfig=/tmp/kubeconfig-486693343 -olmNamespace=openshift-operator-lifecycle-manager -dummyImage=bitnami/nginx:latest -ginkgo.flakeAttempts=3 
INFO[2021-04-10T04:59:58Z] # github.com/operator-framework/operator-lifecycle-manager/test/e2e [github.com/operator-framework/operator-lifecycle-manager/test/e2e.test] 
INFO[2021-04-10T04:59:58Z] test/e2e/installplan_e2e_test.go:129:64: undefined: client 
INFO[2021-04-10T04:59:58Z] test/e2e/installplan_e2e_test.go:139:63: undefined: client 
INFO[2021-04-10T04:59:58Z] test/e2e/installplan_e2e_test.go:229:54: undefined: client 
INFO[2021-04-10T04:59:58Z] FAIL	github.com/operator-framework/operator-lifecycle-manager/test/e2e [build failed] 
```

**Comment by benluddy** [comment]
Found it, that import is introduced with https://github.com/openshift/operator-framework-olm/pull/41 which hasn't merged yet. Let's talk next week about what we can do to avoid this kind of issue -- fixed in the meantime.

/hold cancel
